# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  run:
    desc: Run the project
    cmds:
      - go run .

  check:
    desc: Build and vet the project
    cmds:
      - go build ./...
      - go vet ./...
